// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiUxJyzgohfIZ0NjzLXJxqbXFv3wO1bBo',
    appId: '1:440485747817:web:a1a403b98f9547184fd6f8',
    messagingSenderId: '440485747817',
    projectId: 'ashop-51800',
    authDomain: 'ashop-51800.firebaseapp.com',
    storageBucket: 'ashop-51800.firebasestorage.app',
    measurementId: 'G-N6E807EC79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO558kAvRMXrbS_bs-mk9bkEicmOfyNYk',
    appId: '1:440485747817:android:cb120013de718aab4fd6f8',
    messagingSenderId: '440485747817',
    projectId: 'ashop-51800',
    storageBucket: 'ashop-51800.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGPr1u2HaYel13GJaMGUni-SWTG99EQiA',
    appId: '1:440485747817:ios:d17d263dc0b8144a4fd6f8',
    messagingSenderId: '440485747817',
    projectId: 'ashop-51800',
    storageBucket: 'ashop-51800.firebasestorage.app',
    iosClientId: '440485747817-8jdo4bhm1og7a0fd3nuhs1fi0b1s2gkh.apps.googleusercontent.com',
    iosBundleId: 'com.example.fmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGPr1u2HaYel13GJaMGUni-SWTG99EQiA',
    appId: '1:440485747817:ios:d17d263dc0b8144a4fd6f8',
    messagingSenderId: '440485747817',
    projectId: 'ashop-51800',
    storageBucket: 'ashop-51800.firebasestorage.app',
    iosClientId: '440485747817-8jdo4bhm1og7a0fd3nuhs1fi0b1s2gkh.apps.googleusercontent.com',
    iosBundleId: 'com.example.fmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiUxJyzgohfIZ0NjzLXJxqbXFv3wO1bBo',
    appId: '1:440485747817:web:03929ab5bbc43d154fd6f8',
    messagingSenderId: '440485747817',
    projectId: 'ashop-51800',
    authDomain: 'ashop-51800.firebaseapp.com',
    storageBucket: 'ashop-51800.firebasestorage.app',
    measurementId: 'G-S3X71GNWTD',
  );
}
